#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : librtlsdr
Version  : 0.6.0
Release  : 6
URL      : https://github.com/steve-m/librtlsdr/archive/0.6.0.tar.gz
Source0  : https://github.com/steve-m/librtlsdr/archive/0.6.0.tar.gz
Summary  : C Utility Library
Group    : Development/Tools
License  : GPL-2.0
Requires: librtlsdr-bin = %{version}-%{release}
Requires: librtlsdr-lib = %{version}-%{release}
Requires: librtlsdr-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : pkgconfig(libusb-1.0)

%description
rtl-sdr
turns your Realtek RTL2832 based DVB dongle into a SDR receiver
======================================================================

%package bin
Summary: bin components for the librtlsdr package.
Group: Binaries
Requires: librtlsdr-license = %{version}-%{release}

%description bin
bin components for the librtlsdr package.


%package dev
Summary: dev components for the librtlsdr package.
Group: Development
Requires: librtlsdr-lib = %{version}-%{release}
Requires: librtlsdr-bin = %{version}-%{release}
Provides: librtlsdr-devel = %{version}-%{release}

%description dev
dev components for the librtlsdr package.


%package lib
Summary: lib components for the librtlsdr package.
Group: Libraries
Requires: librtlsdr-license = %{version}-%{release}

%description lib
lib components for the librtlsdr package.


%package license
Summary: license components for the librtlsdr package.
Group: Default

%description license
license components for the librtlsdr package.


%prep
%setup -q -n librtlsdr-0.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538690583
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1538690583
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/librtlsdr
cp COPYING %{buildroot}/usr/share/package-licenses/librtlsdr/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rtl_adsb
/usr/bin/rtl_eeprom
/usr/bin/rtl_fm
/usr/bin/rtl_power
/usr/bin/rtl_sdr
/usr/bin/rtl_tcp
/usr/bin/rtl_test

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/librtlsdr.so
/usr/lib64/pkgconfig/librtlsdr.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/librtlsdr.so.0
/usr/lib64/librtlsdr.so.0.0.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/librtlsdr/COPYING
